### ISSUE TITLE
BDD teszt

### ISSUE THREAD

**Issue by strbikanna** [BME-MIT-IET/iet-hf-2023-nrv#1]
BDD tesztek írása Cucumber eszközökkel.
Cél: az alkalmazás elvárt viselkedésének tesztelése felhasználó számára könnyen érthető módon.

**Comment by jgbor** [comment]
@strbikanna dolgozott rajta, bdd branchen

**Comment by jgbor** [comment]
Statikus analízis miatt változtak a teszteknél függvénynevek, csinálom új branchen
