### ISSUE TITLE
Manuális tesztek

### ISSUE THREAD

**Issue by strbikanna** [BME-MIT-IET/iet-hf-2023-nrv#5]
A játék legtöbb funkcióját manuálisan végigpróbálgatjuk, hogy a nem kívánt vagy helytelen működést detektáljuk és kijavítsuk.

**Comment by strbikanna** [comment]
A játék indulásakor az akciószám 2/3. Javítsuk, hogy 1/3 legyen.

**Comment by strbikanna** [comment]
Legyen egyszerűbb a játék indítása: ne kelljen megadni map elérési útvonalat.

**Comment by jgbor** [comment]
Tesztek tervezése @ZserboZsiraf és @jgbor

**Comment by jgbor** [comment]
A következő funkciókat szeretnénk tesztelni manuálisan:

- Játékos-mező interakció: 
     - A virológus el tud lépni szomszédos mezőbe.
     - Letapogatás egy laborban, aminek a hatására a virológus megtanul egy még nem ismert genetikai kódot.
     - Felszerelés gyűjtése egy óvóhelyen, üres óvóhelyen nem szerez már semmit
     - Már van három felszerelése, ezért nem tud újat felvenni.
     - Anyaggyűjtés raktárban, +5 egységnyit kapunk.
     - Szabad területen nincs akció.
     - Max 3 cselekvés egy körben
     - Fertőző laborban megfertőződik medvevírussal a virológus

- Játékos-játékos interakció:
     - Vakcina / Vírus használatkor az ágens költsége levonódik.
     - Vítustánc ágens hatására véletlenül kezd el lépkedni a virológus, 1 kör erejéig.
     - Blokkoló ágens hatására védve van a virológus ágensektől, 2 kör erejéig.
     - Blokkoló ágens hatására elveszti a saját magára kent ágensek hatását.
     - Bénító ágens alatt álló virológus egy kör erejéig, nem tud interakcióba lépni semmivel.
     - A játékos kifoszt egy bénított virológust.
     - Felejtő ágens hatására a virológus elveszti a megtanult genetikai kódokat.
     - Medve megfertőzi a védtelen virológust

- Játékos-felszerelés interakció
     - Védőköpeny az esetek többségében véd az ágensfelkenéstől
     - Zsák növeli 5-tel a maximális nukleotid és aminosav mennyiséget, de a az aktuális mennyiséget nem
     - Kesztyű visszadobja az ágenst
     - Fejszével megölik a medvét

**Comment by jgbor** [comment]
Felhasználóknak visszajelzések nem egyértelműek akció végrehajtásánál (pl collect), hogy sikeres-e vagy nem

**Comment by jgbor** [comment]
Az infected laboratorykról nem kéne tudnunk, hogy azok ezért a UI-on váátoztattunk

**Comment by ZserboZsiraf** [comment]
Láthatóvá tettük, hogy a felhasználó éppen melyik mezőn van és a nucleotide + amino acid bar-oknál feltüntettük, hogy melyik-melyik.
