### ISSUE TITLE
Statikus Analízis, code review

### ISSUE THREAD

**Issue by jgbor** [BME-MIT-IET/iet-hf-2023-nrv#7]
A kód vizsgálata SonarLint-tel és SonarClouddal

**Comment by jgbor** [comment]
SonarCloud beüzemelése: @Baleg00

**Comment by Baleg00** [comment]
SonarCloud nem üzemelhető be a repo-ra, csak organization owner engedéllyel. Ha ez nem oldódik meg, akkor marad a lokális SonarLint.

**Comment by jgbor** [comment]
Sok TODO komment, függvények nagybetűvel kezdődnek, üres függvények

**Comment by jgbor** [comment]
Elrontott commit miatt minden resetelődött, @Baleg00 dolgozik rajta

**Comment by jgbor** [comment]
doc mappában még kell a doksi, egyébként kész, van hozzá egy előtte és utána kép

**Comment by jgbor** [comment]
Ezzel kész is

**Comment by jgbor** [comment]
Újranyitom esetleges módosításokhoz még
